imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   pdo_mysql
#        host:     "%database_host%"
#        port:     "%database_port%"
#        dbname:   "%database_name%"
#        user:     "%database_user%"
#        password: "%database_password%"
#        charset:  UTF8
#        # if using pdo_sqlite as your database driver:
#        #   1. add the path in parameters.yml
#        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
#        #   2. Uncomment database_path in parameters.yml.dist
#        #   3. Uncomment next line:
#        #     path:     "%database_path%"
#
#    orm:
#        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            
fos_rest:
    service:
        view_handler: fos_rest.custom_view_handler
    view:
        formats:
            json: true
            jsonapi: true
        templating_formats:
            html: false
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        mime_types:
            json: ['application/json', 'application/x-json']
            jsonapi: ['application/vnd.api+json']

fos_elastica:
    clients:
        default: { host: elastic, port: 9200 }
    indexes:
        app:
            finder: ~
            index_name: indash
            types:
                host:
                    dynamic_templates:
                        my_template_1:
                            match: ansible*
                            match_mapping_type: "string"
                            mapping:
                                type: "string"
                                index: "not_analyzed"
                user:
                    mappings:
                        username:
                            type: "string"
                            index: "not_analyzed"
                        password:
                            type: "string"
                            index: "not_analyzed"
                        salt:
                            type: "string"
                            index: "not_analyzed"
                        token:
                            type: "string"
                            index: "not_analyzed"
                note:
#                    serializer:
#                        groups: [elastica, Default]
                        
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
